---
- name: Set up iptables rules
  copy: src=iptables-save dest=/etc/sysconfig/iptables
  notify: restart iptables

- name: Install Python package
  apt: name={{ item }} state=present
  with_items:
   - python
   - iptables
